FROM alpine:3.4

ENV TIMEZONE=Asia/Shanghai
#RUN apk add --update --repository http://dl-2.alpinelinux.org/alpine/edge/testing/
RUN apk --update add wget \
	curl \
	git \
	grep \
	gmp-dev \
	libmcrypt-dev \
	freetype-dev \
	libxpm-dev \
	libwebp-dev \
	libjpeg-turbo-dev \
	libjpeg \
	bzip2-dev \
	openssl-dev \
	krb5-dev \
	libxml2-dev \
	build-base \
	tar \
	make \
	autoconf